<?php
/*
Plugin Name: DDay
Plugin URI: http://mdkart.fr/blog/2007/04/16/plugin-dday-pour-wordpress
Description: This plugin allows you to display DDay's. It also has a spiffy management tool in the administrative console. Fully customizable. 
Author: Mdkart
Author URI: http://mdkart.fr
Version: 0.3.2
Put in /wp-content/plugins/dday/ of your Wordpress installation
Inpsired by :
- DDay plugin by Franck Paul for Dotclear : http://franck.paul.free.fr/dotclear/?2005/03/22/105-plugin-jour-j
- Code of Wp-quotes by zombierobot : http://www.zombierobot.com/wp-quotes/
- Code of Wp-Polls by zombierobot  : http://www.lesterchan.net/wordpress/readme/wp-polls.html


TODO:
- Choix des unités des décomptes plus flexible (+++)
- Solve Bugs if exists
- Version standalone

New in 0.2
- -1 in display before and after => No display
- Widget
- 1 bug fixed Fonction : drag and drope
- Some improvement in the code 
- Nice tooltip : can be de-activate easilly
*/

//Can be modified
$nice_tooltip = 1; // 1 -> Enable nice tootltip when mouse over a DDay.

### DDay Table Name
define('WP_DDAY_TABLE', $table_prefix . 'dday');

### Function: Poll Administration Menu
function wp_dday_admin_menu() 
	{
	add_management_page('Dday', 'Dday', 8, 'dday/edit-dday.php');
	}
add_action('admin_menu', 'wp_dday_admin_menu');

if ($nice_tooltip == 1)
{
add_action('wp_head', 'dday_header');
function dday_header() {	
	echo "\n".'<!-- Start Of Script Generated By DDay -->'."\n";
	echo '<link rel="stylesheet" href="'.get_option('siteurl').'/wp-content/plugins/dday/script/dday.css" type="text/css" media="screen" />'."\n";
	echo '<script type="text/javascript" src="'.get_option('siteurl').'/wp-content/plugins/dday/script/qTip.js"></script>'."\n";
	}
}	
### Recupere les valeurs d'options	
function countdown($ddayID, $option)
{	global $wpdb;
	$item_list = '';
	$data = false;	
	if ( $ddayID !== false )
	{
		if ( intval($ddayID) != $ddayID )
		{	return "<div class=\"error\"><p>Bad Monkey! No banana!</p></div>";
		}
		else
		{	$data = $wpdb->get_results("SELECT * FROM " . WP_DDAY_TABLE . " WHERE ddayID=".$ddayID);
			if ( empty($data) )
			{	return "<div class=\"error\"><p>I couldn't find a DDay linked up with that identifier. Giving up...</p></div>";
			}
			$data = $data[0];}	
	}
	$title = $data->title;
	$date = $data->date;
	$url = $data->url;
	$des = $data->des;
	$nbr_jr_av = $data->nbr_jr_av;
	$nbr_jr_ap = $data->nbr_jr_ap;
	$frq_rpt = $data->frq_rpt;
	$rpt = $data->rpt;
	$format_past = $data->past;		
	$format_yester = $data->yester;		
	$format_tod = $data->tod;		
	$format_imm = $data->imm;		
	$format_tom = $data->tom;		
	$format_futur = $data->futur;
		
	$option_var = $option[0];
	if (empty($format_past)) {$format_past =  $option_var->past;}
	if (empty ($format_yester)) {$format_yester =  $option_var->yester;}
	if (empty ($format_tod)) {$format_tod =  $option_var->tod;}
	if (empty ($format_imm)) {$format_imm =  $option_var->imm;}
	if (empty ($format_tom)) {$format_tom =  $option_var->tom;}
	if (empty ($format_futur)) {$format_futur =  $option_var->futur;}
	
	// get current unix timestamp
	$today = current_time(timestamp, $gmt = 1);
	if ($rpt == 1 or $rpt == 2 or $rpt == 3 or $rpt == 4)
		{
		if ($rpt==1) {$unit = "day";} 
		elseif ($rpt==2) {$unit = "week";}
		elseif($rpt==3) {$unit = "month";}
		elseif($rpt==4) {$unit = "year";}
		$offset = " +".$frq_rpt." ".$unit.($frq_rpt > 1 ? "s" : "");  
		if ($today >= ($date+24*60*60*$nbr_jr_ap)) 
			{
			do 	{
				$date = strtotime(date("Y-m-d H:i:s", $date).$offset);
				} 
			while ($today >= ($date+24*60*60*$nbr_jr_ap));	
			}
		}
		
	$date_day = strtotime(date("Y-m-d 0:0:0", $date));
	$today_day = strtotime(date("Y-m-d 0:0:0", $today));
	$delay_day = round(($date_day - $today_day) / 24 / 60 / 60);
	$delay = $date - $today; // In seconds
	$signe = ($delay >= 0 ? 1 : -1);	
	$delay = abs($delay);
	$delay_hour = floor($delay / 60 / 60);
	$delay -= ($delay_hour * 60 * 60);
	$delay_minute = round($delay / 60);
  
  	# Determine si l'affichage doit etre effectue 
	$display_item = true;
	if (($nbr_jr_av > 0) && ($delay_day > $nbr_jr_av)) 
	{
		$display_item = false;
	} elseif (($nbr_jr_ap > 0) && ((- $delay_day) > $nbr_jr_ap)) 
	{
		$display_item = false;
	} elseif (($signe == -1) && ($nbr_jr_ap == -1)) 
	{
		$display_item = false;
	} elseif (($signe == 1) && ($nbr_jr_av == -1)) 
	{
		$display_item = false;
	}	
	if ($display_item == true) 
	{
		# Mise en place du jour J
		# Debut de l'URL
		if ($url <> '') {
		$item_list .= '<a href="'.$url.'"  title="';			
		}
		else $item_list .= '<span title="';
		if ($des <> '') {
		$item_list .= $des.' : ';
		}
		$item_list .= date ( "d/m/Y H:i:s" , $date ).'" class="dday-title">';
		switch (true) {
			case ($delay_day < -1):
			# C'etait avant-hier ou encore avant
				$format_past = str_replace("%TITLE%", $title, $format_past);
				$format_past = str_replace("%DELAY_DAY%", - $delay_day, $format_past);
				$item_list .= $format_past;
				break;
			case ($delay_day == -1):
			# C'etait hier
				$format_yester = str_replace("%TITLE%", $title, $format_yester);
				$format_yester = str_replace("%DELAY_DAY%", - $delay_day, $format_yester);
				$item_list .= $format_yester;
			break;
			case ($delay_day == 0):
			# C'est aujourd'hui
			if ($signe == -1) {
				# C'est deja passe dans la journee
					$format_tod = str_replace("%TITLE%", $title, $format_tod);
					$item_list .= $format_tod;
				} else {
				# C'est bientot dans la journee
					$format_imm = str_replace("%TITLE%", $title, $format_imm);
					$format_imm = str_replace("%DELAY_DAY%", $delay_day, $format_imm);
					$format_imm = str_replace("%DELAY_HR%", $delay_hour, $format_imm);
					$format_imm = str_replace("%DELAY_MIN%", $delay_minute, $format_imm);
					$item_list .= $format_imm;
					}
			break;
			case ($delay_day == 1):
			# C'est demain
				$format_tom = str_replace("%TITLE%", $title, $format_tom);
				$format_tom = str_replace("%DELAY_DAY%", $delay_day, $format_tom);
				$item_list .= $format_tom;
			break;
			case ($delay_day > 1):
			# C'est apres-demain ou encore plus tard
				$format_futur = str_replace("%TITLE%", $title, $format_futur);
				$format_futur = str_replace("%DELAY_DAY%", $delay_day, $format_futur);
				$item_list .= $format_futur;
			break;
			}
			# Fin de l'URL
			if ($url <> '') {
				$item_list .= '</a>';
			}else $item_list .= '</span>';			
	}
	return $item_list;
}
function wp_dday_list()
{ global $wpdb;
	echo '<ul class=\'dday\'>';
	$ddays = $wpdb->get_results("SELECT ddayID FROM " . WP_DDAY_TABLE . " WHERE ddayID != 1 AND visible='yes' ORDER BY RANK");
	$option = $wpdb->get_results("SELECT * FROM " . WP_DDAY_TABLE . " WHERE ddayID=1");
	if ( empty($option) )
	{	echo "<div class=\"error\"><p>I couldn't find a dday linked up with the options...</p></div>";
		return;
	}
	if ( !empty($ddays) )
	{	foreach ( $ddays as $dday )
		{ 	$ddayID = $dday->ddayID;
			$result = countdown($ddayID, $option);
			if ( !empty($result) )
			{	echo '<li>'.$result.'</li>';
			}
		}		
	}
	else echo 'No DDAY enter yet';
echo '</ul>';
}

add_filter('the_content', 'place_dday', '7');
function place_dday ($content)
{
    $content = preg_replace( "/\[dday=(\d+)\]/ise", "wp_dday_src('$1')", $content); 
    return $content;
}
function wp_dday_src($ddayID)
{ 	global $wpdb;
	$option = $wpdb->get_results("SELECT * FROM " . WP_DDAY_TABLE . " WHERE ddayID=1");
	if ( empty($option) )
	{	echo "<div class=\"error\"><p>I couldn't find a dday linked up with the options...</p></div>";
		return;
	}		
	return countdown($ddayID, $option);
}

function wp_dday($ddayID)
{ 	global $wpdb;
	$option = $wpdb->get_results("SELECT * FROM " . WP_DDAY_TABLE . " WHERE ddayID=1");
	if ( empty($option) )
	{	echo "<div class=\"error\"><p>I couldn't find a dday linked up with the options...</p></div>";
		return;
	}		
	echo countdown($ddayID, $option);
}
?>